Mise en place Docker sur API et CI githubAction

diff --git a/.github/workflows/build_test_react.yml b/.github/workflows/build_test_react.yml
--- a/.github/workflows/build_test_react.yml
+++ b/.github/workflows/build_test_react.yml
@@ -160,3 +160,81 @@ jobs:
       - name: Deploy to Github pages
         id: deployment
         uses: actions/deploy-pages@v4
+
+build-test-deploy-api:
+    needs: build_test
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - name: Build MySQL Image
+        run: docker build -t my-mysql .
+
+      - name: Build Python API Image
+        run: docker build -t my-api ./server
+
+      - name: Create Network
+        run: docker network create stack-net
+
+      - name: Run MySQL Container
+        run: |
+          docker run -d \
+            --name mysql-container \
+            --network stack-net \
+            -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
+            -e MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} \
+            my-mysql
+
+      - name: Wait for MySQL to be ready
+        run: |
+          echo "Waiting for MySQL..."
+          for i in $(seq 1 30); do
+            if docker exec mysql-container mysqladmin ping -h localhost --silent; then
+              echo "MySQL is ready!"
+              break
+            fi
+            echo "Attempt $i/30..."
+            sleep 3
+          done
+
+      - name: Run API Container
+        run: |
+          docker run -d \
+            --name api-container \
+            --network stack-net \
+            -e MYSQL_HOST=${{ secrets.MYSQL_HOST }} \
+            -e MYSQL_USER=${{ secrets.MYSQL_USER }} \
+            -e MYSQL_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
+            -e MYSQL_DB=${{ secrets.MYSQL_DATABASE }} \
+            -p 8000:8000 \
+            my-api
+
+      - name: Wait for API startup
+        run: sleep 10
+
+      - name: Validate API with Curl
+        run: |
+          response=$(curl -s -w "\n%{http_code}" http://localhost:8000/users)
+          http_code=$(echo "$response" | tail -n1)
+          body=$(echo "$response" | head -n -1)
+          echo "Response Body: $body"
+          if [ "$http_code" != "200" ]; then
+            echo "Error: HTTP status $http_code"
+            exit 1
+          fi
+          if echo "$body" | grep -q '"utilisateurs":\[\]'; then
+            echo "Error: User list is empty"
+            exit 1
+          fi
+
+      - name: Push API Image to Docker Hub
+        run: |
+          docker tag my-api ${{ secrets.DOCKERHUB_USERNAME }}/python-api:latest
+          docker push ${{ secrets.DOCKERHUB_USERNAME }}/python-api:latest
